FROM uphy/ubuntu-desktop-jp:20.04

RUN apt update
RUN apt upgrade

RUN apt install -y \
    build-essential libssl-dev zlib1g-dev \
    libbz2-dev libreadline-dev libsqlite3-dev curl llvm \
    libncursesw5-dev tk-dev libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev \
    libopencv-dev git

RUN xxx
