packages = ["pillow","pydantic","pandas"]

[files]
# pyscript のための設定
"{FROM}" = ".."
"{TO}" = "/home/work"

# utils
"{FROM}/src/utils/__init__.py" = "{TO}/src/utils/__init__.py"
"{FROM}/src/utils/base.py" = "{TO}/src/utils/base.py"
"{FROM}/src/utils/card.py" = "{TO}/src/utils/card.py"
"{FROM}/src/utils/deck.py" = "{TO}/src/utils/deck.py"
"{FROM}/src/utils/logger.py" = "{TO}/src/utils/logger.py"

# field
"{FROM}/src/field.py" = "{TO}/src/field.py"

# player
"{FROM}/src/player/__init__.py" = "{TO}/src/player/__init__.py"
"{FROM}/src/player/declear.py" = "{TO}/src/player/declear.py"
"{FROM}/src/player/player.py" = "{TO}/src/player/player.py"
"{FROM}/src/player/charactor.py" = "{TO}/src/player/charactor.py"

# game
"{FROM}/src/game/__init__.py" = "{TO}/src/game/__init__.py"
"{FROM}/src/game/track.py" = "{TO}/src/game/track.py"
"{FROM}/src/game/game.py" = "{TO}/src/game/game.py"
"{FROM}/src/game/vs_series.py" = "{TO}/src/game/vs_series.py"

# bid
"{FROM}/src/bid/__init__.py" = "{TO}/src/bid/__init__.py"
"{FROM}/src/bid/bid.py" = "{TO}/src/bid/bid.py"

## pyscipt で利用する処理
"./src/utils/games.py" = "/pyscript/pyscript/src/utils/games.py"
"./src/utils/button.py" = "/pyscript/pyscript/src/utils/button.py"